In [167]:
import numpy as np
import math

In [90]:
matrix = np.zeros((61189,21))

In [158]:
classProbMatrix = np.zeros((21,))

In [159]:
matrix

array([[   0.,    0.,    0., ...,    0.,    0.,    0.],
       [   0.,   13.,   60., ...,   10.,    0.,    0.],
       [   0.,   63.,   59., ...,  154.,   39.,   45.],
       ..., 
       [   0.,    0.,    0., ...,    0.,    0.,    0.],
       [   0.,    0.,    0., ...,    0.,    0.,    0.],
       [   0.,    0.,    0., ...,    0.,    0.,    0.]])

In [160]:
rowIndex = 1
docIdToLabel = {}
with open('data/train.label', 'r') as trainLabels:
    for line in trainLabels:
        label = int(line.rstrip('\n'))
        docIdToLabel[str(rowIndex)] = label
        classProbMatrix[label] = classProbMatrix[label] + 1
        rowIndex = rowIndex + 1

In [201]:
totalTrainingExamples = classProbMatrix.sum()
classProbMatrix = np.log2(classProbMatrix/totalTrainingExamples)
classProbMatrix

/Users/esteban/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:2: RuntimeWarning: divide by zero encountered in log2
  from ipykernel import kernelapp as app


array([       -inf, -4.55318128, -4.27767752, -4.30020054, -4.26285518,
       -4.29265373, -4.25061851, -4.27519653, -4.25061851, -4.24090336,
       -4.24575276, -4.2360702 , -4.24575276, -4.25305756, -4.24575276,
       -4.24818358, -4.23365968, -4.36995946, -4.32052052, -4.60209088,
       -4.90548303])

In [93]:
with open('data/train.data','r') as trainData:
    for line in trainData:
        values = line.rstrip('\n').split(" ")
        label = docIdToLabel[values[0]]
        wordId = int(values[1])
        wordCount = int(values[2])
        matrixValue = matrix[wordId,label]
        newValue = matrixValue + wordCount
        matrix[wordId,label] = newValue
matrix

array([[   0.,    0.,    0., ...,    0.,    0.,    0.],
       [   0.,   13.,   60., ...,   10.,    0.,    0.],
       [   0.,   63.,   59., ...,  154.,   39.,   45.],
       ..., 
       [   0.,    0.,    0., ...,    0.,    0.,    0.],
       [   0.,    0.,    0., ...,    0.,    0.,    0.],
       [   0.,    0.,    0., ...,    0.,    0.,    0.]])

In [94]:
matrix[:,1].sum()

148812.0

In [60]:
vocabSize = 61188.0

In [141]:
probMatrix = np.zeros((61189,21))

In [142]:
beta = 1.0/vocabSize

In [143]:

for v in range(1,21):
    totalWordsInClassV = matrix[:,v].sum()
    if totalWordsInClassV > 1:
        print(totalWordsInClassV)
    for w in range(1,61189):
        wordId = int(w)
        label = int(v)
        countOfWInClassV = matrix[w,v]
        probabilityOfWGivenV = ((countOfWInClassV) + beta)/ (totalWordsInClassV + beta*vocabSize)
        probMatrix[wordId,label] = probabilityOfWGivenV
probMatrix

148812.0
110358.0
90767.0
99146.0
86190.0
152846.0
61094.0
114102.0
102631.0
107898.0
141267.0
200456.0
103173.0
155338.0
153714.0
201267.0
175914.0
254805.0
186426.0
119096.0


array([[  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   8.73580691e-05,   5.43680319e-04, ...,
          3.92456078e-05,   8.76647364e-11,   1.37224899e-10],
       [  0.00000000e+00,   4.23350220e-04,   5.34618983e-04, ...,
          6.04381437e-04,   2.09197253e-04,   3.77843408e-04],
       ..., 
       [  0.00000000e+00,   1.09822891e-10,   1.48090086e-10, ...,
          6.41392817e-11,   8.76647364e-11,   1.37224899e-10],
       [  0.00000000e+00,   1.09822891e-10,   1.48090086e-10, ...,
          6.41392817e-11,   8.76647364e-11,   1.37224899e-10],
       [  0.00000000e+00,   1.09822891e-10,   1.48090086e-10, ...,
          6.41392817e-11,   8.76647364e-11,   1.37224899e-10]])

In [202]:
probMatrix = np.log2(probMatrix)
probMatrix

/Users/esteban/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in log2
  if __name__ == '__main__':


array([[        -inf,         -inf,         -inf, ...,         -inf,
                -inf,         -inf],
       [        -inf, -13.48269951, -10.84495377, ..., -14.63710927,
        -33.40921242, -32.76273867],
       [        -inf, -11.20586074, -10.86920131, ..., -10.69225303,
        -12.22284847, -11.36992393],
       ..., 
       [        -inf, -33.08410216, -32.65280589, ..., -33.86000085,
        -33.40921242, -32.76273867],
       [        -inf, -33.08410216, -32.65280589, ..., -33.86000085,
        -33.40921242, -32.76273867],
       [        -inf, -33.08410216, -32.65280589, ..., -33.86000085,
        -33.40921242, -32.76273867]])

In [147]:
for i in range(0,61188):
    value = probMatrix[i,2]
    if value == 0.0:
        print(i,value)

0 0.0


In [149]:
probMatrix.shape

(61189, 21)

In [154]:
testMatrix = np.zeros((7506,61189))

In [155]:
rowIndex = 1
docIdToTestLabel = {}
with open('data/test.label', 'r') as testLabels:
    for line in testLabels:
        docIdToTestLabel[str(rowIndex)] = int(line.rstrip('\n'))
        rowIndex = rowIndex + 1


In [156]:
with open('data/test.data','r') as testData:   
    for line in testData:
        values = line.rstrip('\n').split(" ")
        label = docIdToTestLabel[values[0]]
        docId = int(values[0])
        wordId = int(values[1])
        wordCount = int(values[2])
        testMatrix[docId,wordId] = wordCount
testMatrix

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  2.]])

In [204]:
#classifyMatrix = np.zeros((7506,))
classifyMatrix = []

In [206]:
i = 1
for n in range(1,7506):
    p = 0.0
    c = 0
    if i == 2000:
        print("processed 2000")
    if i == 4000:
        print("processed 4000")
    if i == 6000:
        print("processed 6000")
    
    for v in range(1,21):
        pv = classProbMatrix[v]
        sum = 0.0
        for w in range(1,61189):
            if testMatrix[n,w] != 0.0:
                sum = sum + testMatrix[n,w] * probMatrix[w,v]
        prob = pv + sum
        #classifyMatrix[n,v] = prob
        if p == 0.0 or prob > p:
            p = prob
            c = v
    classifyMatrix.append(c)
    i = i + 1
 
print("done...")





processed 2000
processed 4000
processed 6000
done...


TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [215]:
docIdToTestLabel

{'2869': 8,
 '5099': 14,
 '2302': 7,
 '1984': 6,
 '1941': 6,
 '4152': 11,
 '2713': 8,
 '1689': 5,
 '4469': 12,
 '6783': 18,
 '6633': 18,
 '4361': 12,
 '2027': 6,
 '5321': 14,
 '6502': 17,
 '6607': 18,
 '5672': 15,
 '6049': 16,
 '1671': 5,
 '5954': 16,
 '319': 2,
 '1656': 5,
 '5502': 15,
 '3534': 10,
 '3824': 10,
 '2567': 7,
 '5441': 15,
 '3504': 10,
 '6753': 18,
 '6810': 18,
 '3017': 8,
 '6624': 18,
 '7024': 19,
 '2705': 8,
 '810': 3,
 '2903': 8,
 '361': 2,
 '3791': 10,
 '133': 1,
 '4834': 13,
 '3546': 10,
 '2951': 8,
 '2719': 8,
 '5706': 15,
 '5780': 15,
 '6527': 17,
 '7160': 19,
 '5048': 14,
 '3493': 10,
 '4589': 12,
 '5907': 16,
 '2404': 7,
 '883': 3,
 '2452': 7,
 '6498': 17,
 '3123': 9,
 '7040': 19,
 '4884': 13,
 '3510': 10,
 '249': 1,
 '5209': 14,
 '187': 1,
 '2491': 7,
 '449': 2,
 '6704': 18,
 '2667': 8,
 '4461': 12,
 '4758': 13,
 '7290': 20,
 '5170': 14,
 '247': 1,
 '1641': 5,
 '1275': 4,
 '4447': 12,
 '2343': 7,
 '425': 2,
 '2178': 6,
 '6956': 19,
 '279': 1,
 '1244': 4,
 '3744'

In [217]:
file = open("classify.txt", "w")
errorCount = 0
index = 1
for v in classifyMatrix:
    if v != docIdToTestLabel[str(index)]:
        errorCount = errorCount + 1
    index = index + 1
        
print(errorCount)

1612


In [208]:
len(classifyMatrix)

7505

In [212]:
classifyMatrix[7503]

20